# Generated by Django 5.1.7 on 2025-04-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='processing', max_length=20),
        ),
    ]
