# Generated by Django 5.1.7 on 2025-04-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_appointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
    ]
